SELECT
VCD.guestchecklineitemid,
VCD.MAJORGROUPNAME GRUPO_MAJOR,
VCD.FAMILYGROUPNAME GRUPO_FAMILIA,
DECODE (VCD.REVENUECENTERID, 10650,'BAR',
                                    10651,'TIENDA',
                                    10652,'SPA',
                                    11100,'HSK',
                                    10351,'RESTAURANTE',
                                    11100,'COC. PERSONAL') RVC,
VCD.BUSINESSDATE FECHA,
VCH.CHECKNUM NRO_CHECK,
VCD.LINETOTAL VALOR,
VCD.TRANSEMPNAME VENDEDOR,
VCD.TRANSEMPNAME GARZON,
TN.TENDERNAME FORMA_PAGO,
VCH.NUMGUESTS GUEST,
VCH.SERVICECHARGETOTAL SERVICE_CHARGE,
TO_CHAR(VCD.TRANSDATETIME,'HH:MM:SS') TIME,
VCD.VOIDFLAGTF ANULACION,
VCD.REASONNAME ANULACION_RAZON

  FROM VMM_CHECK_DETAILS VCD, 
       VMM_CHECK_HEADERS VCH
      ,(SELECT  MAJORGROUPNAME,
               FAMILYGROUPNAME,
               guestchecklineitemid ,
               TENDERNAME,
               BUSINESSDATE,
               REVENUECENTERID,
               GUESTCHECKID
         FROM VMM_CHECK_DETAILS
        WHERE TENDERNAME IS NOT NULL
         AND LINETOTAL <> 0
  AND REVENUECENTERID <> '13452') TN
  WHERE VCD.BUSINESSDATE >= '05-SEP-19'
  AND VCD.GUESTCHECKID = VCH.GUESTCHECKID
  AND VCD.LINETOTAL <> 0
  AND VCD.REVENUECENTERID <> '13452'
  AND VCD.BUSINESSDATE = TN.BUSINESSDATE
  AND VCD.GUESTCHECKID = TN.GUESTCHECKID
  AND VCH.GUESTCHECKID = TN.GUESTCHECKID
  AND vcd.guestchecklineitemid = TN.guestchecklineitemid
 -- AND VCD.guestchecklineitemid IN (39618)
  
